//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebWriter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>biblebites</string>
  <string>bibleclass</string>
  <string>contact</string>
  <string>covid19</string>
  <string>cyc-reunion</string>
  <string>errors</string>
  <string>events</string>
  <string>free_offers</string>
  <string>gallery</string>
  <string>images</string>
  <string>information_links</string>
  <string>manage</string>
  <string>news</string>
  <string>php</string>
  <string>private</string>
  <string>programme</string>
  <string>prophecy</string>
  <string>public_meetings</string>
  <string>Rugeley</string>
  <string>scripts</string>
  <string>seminars</string>
  <string>styles</string>
  <string>test</string>
  <string>visit</string>
  <string>what_we_believe</string>
  <string>where_we_are</string>
  <string>youthgroup</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LegitDirectories {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LegitDirectories"]));
            }
            set {
                this["LegitDirectories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection EmailRecipients {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EmailRecipients"]));
            }
            set {
                this["EmailRecipients"] = value;
            }
        }
    }
}
